service: lambda-environment

frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage,"qa"}
  environment:
    ${file(./config/env.${self:provider.stage}.json)}

functions:
  commit-message-scheduler:
    handler: handler.scheduler
