service: lambda-environment

frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  commit-message-scheduler:
    handler: handler.scheduler
